# Generated by Django 5.2.3 on 2025-06-26 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='viagens',
            new_name='Viagen',
        ),
    ]
