# Generated by Django 5.2.3 on 2025-06-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0002_rename_viagens_viagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=20)),
                ('data', models.DateTimeField()),
                ('nota_fiscal', models.URLField()),
            ],
        ),
    ]
