# Generated by Django 5.2.3 on 2025-06-27 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0003_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='viagem',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='viagens.viagen'),
            preserve_default=False,
        ),
    ]
