# Generated by Django 5.2.3 on 2025-06-27 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0004_despesa_viagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='viagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='viagens.viagen'),
        ),
    ]
