# Generated by Django 5.2.3 on 2025-06-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0005_alter_despesa_viagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='imagem',
            field=models.ImageField(default=1, upload_to='despesas/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='nota_fiscal',
            field=models.URLField(blank=True),
        ),
    ]
