# Generated by Django 5.2.3 on 2025-06-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0006_despesa_imagem_alter_despesa_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='nota_fiscal',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
