# Generated by Django 5.2.3 on 2025-06-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0008_alter_despesa_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagen',
            name='colaborador',
            field=models.CharField(default='Fernando Pereira da Trindade', max_length=50),
        ),
        migrations.AddField(
            model_name='viagen',
            name='empresa',
            field=models.CharField(default='Smart Picking Soluções Digitais Ltda', max_length=50),
        ),
        migrations.AddField(
            model_name='viagen',
            name='motivo',
            field=models.CharField(default='Implantação DRL Parte 2', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viagen',
            name='retorno',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viagen',
            name='saida',
            field=models.CharField(default='Apucarana', max_length=20),
        ),
        migrations.AddField(
            model_name='viagen',
            name='setor',
            field=models.CharField(default='Smart', max_length=10),
        ),
    ]
