# Generated by Django 5.2.3 on 2025-06-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0009_viagen_colaborador_viagen_empresa_viagen_motivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saida')], default='S', max_length=1),
        ),
    ]
