# Generated by Django 5.2.3 on 2025-08-07 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0010_despesa_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=20)),
                ('empresa', models.CharField(default='Smart Picking Soluções Digitais Ltda', max_length=50)),
                ('setor', models.CharField(default='Smart', max_length=10)),
                ('colaborador', models.CharField(default='Fernando Pereira da Trindade', max_length=50)),
                ('retorno', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=50)),
                ('saida', models.CharField(default='Apucarana', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('nota_fiscal', models.URLField(blank=True, null=True)),
                ('imagem', models.ImageField(upload_to='despesas/')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saida')], default='S', max_length=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='viagens.viagem')),
            ],
        ),
        migrations.DeleteModel(
            name='Despesa',
        ),
        migrations.DeleteModel(
            name='Viagen',
        ),
    ]
