# Generated by Django 5.2.3 on 2025-08-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0011_viagem_transacaofinanceira_delete_despesa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacaofinanceira',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='despesas/'),
        ),
    ]
