# Generated by Django 5.2.3 on 2025-08-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0012_alter_transacaofinanceira_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacaofinanceira',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viagem',
            name='colaborador',
            field=models.CharField(max_length=50),
        ),
    ]
