# Generated by Django 5.2.3 on 2025-08-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0013_alter_transacaofinanceira_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacaofinanceira',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
