# Generated by Django 5.2.3 on 2025-09-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0014_alter_transacaofinanceira_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='destino',
            field=models.CharField(max_length=50),
        ),
    ]
