# Generated by Django 5.2.4 on 2025-10-11 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0002_alter_equipamento_observacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstruturaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, unique=True)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_item', models.CharField(help_text='Código único do item (SKU)', max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('M', 'Metro'), ('KG', 'Quilograma'), ('L', 'Litro')], default='UN', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('idOrdemServico', models.AutoField(primary_key=True, serialize=False)),
                ('solicitante', models.CharField(max_length=100)),
                ('localExecucao', models.CharField(max_length=100)),
                ('Projeto', models.CharField(max_length=100)),
                ('Transportadora', models.CharField(max_length=100)),
                ('codigoRastreio', models.CharField(max_length=100, null=True)),
                ('dataInicio', models.DateTimeField()),
                ('dataTermino', models.DateTimeField(null=True)),
                ('NFEntrada', models.CharField(max_length=50, null=True)),
                ('NFSaida', models.CharField(max_length=50, null=True)),
                ('defeitoInformado', models.TextField()),
                ('diagnosticoTecnico', models.TextField(null=True)),
                ('servicoRealizado', models.TextField(null=True)),
                ('tecnicoResponsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
        migrations.CreateModel(
            name='ProdutoFabricado',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Atividades.item')),
                ('custo_producao_calculado', models.DecimalField(decimal_places=2, default=0.0, help_text='Custo calculado com base na estrutura de produto (BOM).', max_digits=10)),
                ('tempo_de_fabricacao_h', models.FloatField(default=0, help_text='Tempo estimado de fabricação em horas.')),
                ('tempo_de_garantia_meses', models.PositiveIntegerField(default=0, help_text='Tempo de garantia em meses para o cliente final.')),
            ],
            options={
                'verbose_name': 'Produto Fabricado',
                'verbose_name_plural': 'Produtos Fabricados',
            },
            bases=('Atividades.item',),
        ),
        migrations.AddField(
            model_name='estruturaproduto',
            name='componente_filho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usado_em', to='Atividades.item'),
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Atividades.item')),
                ('preco_custo_compra', models.DecimalField(decimal_places=2, help_text='Custo de aquisição do item do fornecedor.', max_digits=10)),
                ('fornecedor_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Atividades.fornecedor')),
            ],
            options={
                'verbose_name': 'Matéria-Prima',
                'verbose_name_plural': 'Matérias-Primas',
            },
            bases=('Atividades.item',),
        ),
        migrations.AddField(
            model_name='estruturaproduto',
            name='produto_pai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='Atividades.produtofabricado'),
        ),
        migrations.AlterUniqueTogether(
            name='estruturaproduto',
            unique_together={('produto_pai', 'componente_filho')},
        ),
    ]
