# Generated by Django 5.2.4 on 2025-10-13 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0003_estruturaproduto_fornecedor_item_ordemservico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('NI', 'Não Iniciado'), ('IM', 'Implantação'), ('FN', 'Finalizado'), ('EN', 'Enviado'), ('PR', 'Produção'), ('AG', 'Aguardando GOLIVE'), ('GO', 'GOLIVE')], default='N', max_length=2)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='preco_custo_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Custo de aquisição do item do fornecedor.', max_digits=10),
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('dataEmissao', models.DateTimeField()),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atividades.fornecedor')),
            ],
        ),
    ]
