# Generated by Django 5.2.4 on 2025-10-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0004_projeto_alter_materiaprima_preco_custo_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
