# Generated by Django 5.2.4 on 2025-10-13 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0005_alter_projeto_data_inicio_alter_projeto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unidade_medida',
            field=models.CharField(choices=[('UN', 'Unidade'), ('M', 'Metro'), ('CM', 'Centímetro'), ('KG', 'Quilograma'), ('L', 'Litro')], default='UN', max_length=3),
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atividades.item')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atividades.projeto')),
            ],
        ),
    ]
