# Generated by Django 5.2.4 on 2025-10-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0006_alter_item_unidade_medida_demanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='quantidade',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
