# Generated by Django 5.2.3 on 2025-10-13 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0007_alter_demanda_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='idAtividade',
        ),
        migrations.AddField(
            model_name='atividade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='projeto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Atividades.projeto'),
            preserve_default=False,
        ),
    ]
