# Generated by Django 5.2.3 on 2025-10-13 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0008_remove_atividade_idatividade_atividade_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='responsavel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='tipoAtividade',
            field=models.CharField(choices=[('M', 'MONTAGEM'), ('E', 'EMBALAGEM'), ('MA', 'MANUTENÇÃO')], default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atividade',
            name='situacao',
            field=models.CharField(choices=[('P', 'PENDENTE'), ('C', 'FINALIZADA')], max_length=1),
        ),
        migrations.CreateModel(
            name='produtoFabricadoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=10)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atividades.atividade')),
                ('produtoFabricado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atividades.produtofabricado')),
            ],
        ),
    ]
