# Generated by Django 5.2.4 on 2025-10-15 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0009_atividade_responsavel_atividade_tipoatividade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas', to='Atividades.projeto'),
        ),
    ]
