# Generated by Django 5.2.4 on 2025-10-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0010_alter_demanda_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='NotaFiscal',
        ),
    ]
