# Generated by Django 5.2.4 on 2025-10-15 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0011_demanda_descricao_delete_notafiscal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demanda',
            old_name='descricao',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='Projeto',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='idOrdemServico',
        ),
        migrations.AddField(
            model_name='demanda',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='localExecucao',
            field=models.CharField(choices=[('E', 'Empresa'), ('C', 'Cliente')], max_length=1),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='projeto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='Atividades.projeto'),
            preserve_default=False,
        ),
    ]
