# Generated by Django 5.2.4 on 2025-10-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0012_rename_descricao_demanda_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
