# Generated by Django 5.2.4 on 2025-10-18 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0013_alter_demanda_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='dataFinal',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='situacao',
            field=models.CharField(choices=[('P', 'PENDENTE'), ('C', 'FINALIZADA')], default='P', max_length=1),
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(db_index=True, max_length=100, unique=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Atividades.produtofabricado')),
                ('projeto_alocado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Atividades.projeto')),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='equipamentos',
            field=models.ManyToManyField(blank=True, related_name='atividades', to='Atividades.equipamento'),
        ),
        migrations.DeleteModel(
            name='produtoFabricadoAtividade',
        ),
    ]
