# Generated by Django 5.2.4 on 2025-10-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0014_atividade_observacoes_alter_atividade_datafinal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
    ]
