# Generated by Django 5.2.4 on 2025-10-25 16:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0016_cliente_ordemcompra_ordempoducao_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(default=None, max_length=18, unique=True, verbose_name='CNPJ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='dataCadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscricoEstatual',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nomeFantasia',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='razaoSocial',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='uf',
            field=models.CharField(max_length=2, verbose_name='UF'),
        ),
    ]
