# Generated by Django 5.2.4 on 2025-10-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0017_cliente_cnpj_cliente_datacadastro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='dataCadastro',
            new_name='data_cadastro',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nomeFantasia',
            new_name='nome_fantasia',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='inscricoEstatual',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='razaoSocial',
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscricao_statual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(default=None, max_length=255, verbose_name='Razão social'),
            preserve_default=False,
        ),
    ]
