# Generated by Django 5.2.4 on 2025-10-25 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0018_rename_datacadastro_cliente_data_cadastro_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Empresa',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='id_cliente',
        ),
        migrations.AddField(
            model_name='endereco',
            name='id_empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='Atividades.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
    ]
