# Generated by Django 5.2.4 on 2025-10-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0019_rename_cliente_empresa_remove_endereco_id_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordempoducao',
            name='teste',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
