# Generated by Django 5.2.4 on 2025-10-25 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0020_ordempoducao_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordempoducao',
            name='teste',
        ),
    ]
