# Generated by Django 5.2.4 on 2025-10-25 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0021_remove_ordempoducao_teste'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão social')),
                ('nome_contato', models.CharField(max_length=100, verbose_name='Nome para Contato')),
                ('telefone', models.CharField(max_length=20)),
                ('observacoes', models.TextField(verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='empresa',
            name='inscricao_statual',
            field=models.CharField(blank=True, help_text='Obrigatório para emissão de NF-e de produto.', max_length=20, null=True, verbose_name='Inscrição Estadual(IE)'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome_fantasia',
            field=models.CharField(max_length=150, verbose_name='Nome Fantasia'),
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='O ID do objeto (Projeto 5, OS 10)', null=True, verbose_name='ID do Motivo')),
                ('motivo_avulso', models.CharField(blank=True, help_text='Usar se o envio não estiver ligado a um objeto.', max_length=200, verbose_name='Motivo (se avulso)')),
                ('aos_cuidados', models.CharField(blank=True, max_length=100, verbose_name='A/C (Aos Cuidados de)')),
                ('codigo_rastreio', models.CharField(blank=True, max_length=50, verbose_name='Cód. Rastreio')),
                ('content_type', models.ForeignKey(blank=True, help_text='O motivo do Envio (Projeto, Ordem de Serviço, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Tipo do Motivo')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_como_destinatario', to='Atividades.endereco', verbose_name='Destinatário')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_como_remetente', to='Atividades.endereco', verbose_name='Remetente')),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Atividades.transportadora', verbose_name='Transportadora')),
            ],
            options={
                'verbose_name': 'Envio (Etiqueta)',
                'verbose_name_plural': 'Envios (Etiquetas)',
            },
        ),
    ]
