# Generated by Django 5.2.4 on 2025-10-25 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0022_transportadora_alter_empresa_inscricao_statual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='motivo_avulso',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='transportadora',
            name='ativo',
        ),
        migrations.AddField(
            model_name='envio',
            name='ordem_servico',
            field=models.ForeignKey(default=1, help_text='A OS que justifica este envio.', on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='Atividades.ordemservico', verbose_name='Ordem de Serviço'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='observacoes',
            field=models.BooleanField(default=True),
        ),
    ]
