# Generated by Django 5.2.4 on 2025-10-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0023_remove_envio_content_type_remove_envio_motivo_avulso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportadora',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='observacoes',
            field=models.TextField(verbose_name='Observações'),
        ),
    ]
