# Generated by Django 5.2.4 on 2025-10-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0024_transportadora_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportadora',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
