# Generated by Django 5.2.4 on 2025-10-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0025_alter_transportadora_observacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportadora',
            name='nome_contato',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome para Contato'),
        ),
    ]
