# Generated by Django 5.2.4 on 2025-10-26 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0026_alter_transportadora_nome_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefeitoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defeito', models.CharField(max_length=255)),
                ('efeito', models.CharField(max_length=255)),
                ('causa', models.CharField(blank=True, max_length=255)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defeitos', to='Atividades.produtofabricado')),
            ],
        ),
        migrations.DeleteModel(
            name='Problema',
        ),
        migrations.AlterModelOptions(
            name='envio',
            options={'verbose_name': 'Envio', 'verbose_name_plural': 'Envios'},
        ),
        migrations.RenameField(
            model_name='ordemservico',
            old_name='Transportadora',
            new_name='transportadora',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='transportadora',
        ),
        migrations.AddField(
            model_name='envio',
            name='transportadora_padrao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Atividades.transportadora', verbose_name='Transportadora_Padrão'),
            preserve_default=False,
        ),
    ]
