# Generated by Django 5.2.4 on 2025-10-26 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0027_defeitocomponente_delete_problema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defeitocomponente',
            name='componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defeitos', to='Atividades.item'),
        ),
    ]
