# Generated by Django 5.2.4 on 2025-10-26 13:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0028_alter_defeitocomponente_componente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defeitocomponente',
            name='componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registro_defeitos', to='Atividades.item'),
        ),
        migrations.CreateModel(
            name='DefeinoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_identificacao', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data Identificado')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_defeitos', to='Atividades.equipamento')),
                ('falha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defeitos_equipamentos', to='Atividades.equipamento')),
            ],
            options={
                'ordering': ['equipamento'],
            },
        ),
    ]
