# Generated by Django 5.2.4 on 2025-10-26 18:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0029_alter_defeitocomponente_componente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdemPoducao',
            new_name='OrdemProducao',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='ordem_servico',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='remetente',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='transportadora_padrao',
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nome_fantasia', 'razao_social']},
        ),
        migrations.RenameField(
            model_name='ordemservico',
            old_name='NFEntrada',
            new_name='nota_entrada',
        ),
        migrations.RenameField(
            model_name='ordemservico',
            old_name='NFSaida',
            new_name='nota_saida',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='codigoRastreio',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='defeitoInformado',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='diagnosticoTecnico',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='localExecucao',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='servicoRealizado',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='tecnicoResponsavel',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='transportadora',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='local_execucao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Atividades.endereco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tecnico_responsavel',
            field=models.ManyToManyField(related_name='ordem_serivico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='defeitocomponente',
            name='efeito',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='dataInicio',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Atividades.empresa'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('NI', 'Não Iniciado'), ('IM', 'Implantação'), ('FN', 'Finalizado'), ('EN', 'Enviado'), ('PR', 'Produção'), ('AG', 'Aguardando GOLIVE'), ('GO', 'GOLIVE')], default='NI', max_length=2),
        ),
        migrations.CreateModel(
            name='ServicoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('T', 'TROCAR'), ('M', 'MANUTENÇÃO'), ('J', 'JUMPER'), ('R', 'RESOLDAR')], max_length=1)),
                ('obeservacao', models.TextField()),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Atividades.item')),
            ],
        ),
        migrations.CreateModel(
            name='DefeitoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_identificacao', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data Identificado')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_defeitos', to='Atividades.equipamento')),
                ('falha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defeitos_equipamentos', to='Atividades.defeitocomponente')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Atividades.ordemservico')),
                ('acao_necessaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Atividades.servicorealizado')),
            ],
            options={
                'ordering': ['equipamento'],
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aos_cuidados', models.CharField(blank=True, max_length=100, verbose_name='A/C (Aos Cuidados de)')),
                ('codigo_rastreio', models.CharField(blank=True, max_length=50, verbose_name='Cód. Rastreio')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_como_destinatario', to='Atividades.endereco', verbose_name='Destinatário')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_como_remetente', to='Atividades.endereco', verbose_name='Remetente')),
                ('transportadora_padrao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Atividades.transportadora', verbose_name='Transportadora_Padrão')),
            ],
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='transporte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Atividades.transporte'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DefeinoEquipamento',
        ),
        migrations.DeleteModel(
            name='Envio',
        ),
    ]
