# Generated by Django 5.2.4 on 2025-10-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0030_rename_ordempoducao_ordemproducao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='dataTermino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
