# Generated by Django 5.2.4 on 2025-10-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0031_alter_ordemservico_datatermino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='nota_entrada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='nota_saida',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
