# Generated by Django 5.2.4 on 2025-10-26 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0032_alter_ordemservico_nota_entrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporte',
            name='codigo_rastreio',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='transportadora_padrao',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='codigo_rastreio',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cód. Rastreio'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='transportadora_padrao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Atividades.transportadora', verbose_name='Transportadora_Padrão'),
            preserve_default=False,
        ),
    ]
