# Generated by Django 5.2.4 on 2025-10-26 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0033_remove_transporte_codigo_rastreio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemservico',
            old_name='dataInicio',
            new_name='data_inicio',
        ),
    ]
