# Generated by Django 5.2.3 on 2025-10-30 21:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0034_rename_datainicio_ordemservico_data_inicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemproducao',
            options={'ordering': ['-data_emissao'], 'verbose_name': 'Ordem de Produção', 'verbose_name_plural': 'Ordens de Produção'},
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='codigo_op',
            field=models.CharField(blank=True, help_text='Código único da Ordem (ex: OP-00123)', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='data_conclusao_real',
            field=models.DateTimeField(blank=True, help_text='Data e hora que a produção foi finalizada', null=True),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='data_emissao',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data em que a OP foi criada no sistema'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='data_inicio_real',
            field=models.DateTimeField(blank=True, help_text='Data e hora que a produção realmente começou', null=True),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='data_prevista_conclusao',
            field=models.DateField(blank=True, help_text='Data limite para a conclusão da produção', null=True),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='produto',
            field=models.ForeignKey(default=12, help_text='O produto final que será fabricado', on_delete=django.db.models.deletion.PROTECT, related_name='ordens_producao', to='Atividades.produtofabricado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='projeto',
            field=models.ForeignKey(blank=True, help_text='Projeto ao qual esta OP está vinculada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_producao', to='Atividades.projeto'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='quantidade_planejada',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade que deve ser produzida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='quantidade_produzida',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade real que foi produzida com sucesso'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='status',
            field=models.CharField(choices=[('PLANEJADA', 'Planejada'), ('LIBERADA', 'Liberada para Produção'), ('EM_PRODUCAO', 'Em Produção'), ('QUALIDADE', 'Controle de Qualidade'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], db_index=True, default='PLANEJADA', max_length=20),
        ),
    ]
