# Generated by Django 5.2.3 on 2025-11-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0035_alter_ordemproducao_options_ordemproducao_codigo_op_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='situacao',
        ),
        migrations.AddField(
            model_name='atividade',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='dataFinal',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='produtofabricado',
            name='custo_producao_calculado',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Custo calculado com base na estrutura de produto (BOM).', max_digits=10),
        ),
    ]
