# Generated by Django 5.2.3 on 2025-11-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0036_remove_atividade_situacao_atividade_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividade',
            old_name='dataFinal',
            new_name='data_final',
        ),
        migrations.RenameField(
            model_name='atividade',
            old_name='dataInicial',
            new_name='data_inicial',
        ),
        migrations.RenameField(
            model_name='atividade',
            old_name='tipoAtividade',
            new_name='tipo_atividade',
        ),
    ]
