# Generated by Django 5.2.3 on 2025-11-05 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0037_rename_datafinal_atividade_data_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='data_inicial',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
