# Generated by Django 5.2.4 on 2025-11-06 01:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0038_alter_atividade_data_inicial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemproducao',
            options={'ordering': ['-data_criacao', 'status'], 'verbose_name': 'Ordem de Produção', 'verbose_name_plural': 'Ordens de Produção'},
        ),
        migrations.RemoveField(
            model_name='ordemproducao',
            name='codigo_op',
        ),
        migrations.RemoveField(
            model_name='ordemproducao',
            name='data_conclusao_real',
        ),
        migrations.RemoveField(
            model_name='ordemproducao',
            name='data_emissao',
        ),
        migrations.RemoveField(
            model_name='ordemproducao',
            name='data_inicio_real',
        ),
        migrations.RemoveField(
            model_name='ordemproducao',
            name='data_prevista_conclusao',
        ),
        migrations.RemoveField(
            model_name='ordemproducao',
            name='solicitante',
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='custo_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo calculado no momento do planejamento (Qtd * Custo do BOM)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='custo_real',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo real apurado após o consumo de materiais.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='data_real_termino',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão Real'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='demanda_origem',
            field=models.ForeignKey(blank=True, help_text='Demanda de cliente/projeto que originou esta OP.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_geradas', to='Atividades.demanda'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='tempo_execucao_preivista',
            field=models.DateField(blank=True, null=True, verbose_name='Término Previsto'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='produto',
            field=models.ForeignKey(help_text='O item que será produzido.', on_delete=django.db.models.deletion.PROTECT, to='Atividades.produtofabricado'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='projeto',
            field=models.ForeignKey(blank=True, help_text='Projeto ao qual esta produção está vinculada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_producao', to='Atividades.projeto'),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='quantidade_planejada',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Quantidade que se planeja produzir.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='quantidade_produzida',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantidade realmente finalizada.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='status',
            field=models.CharField(choices=[('PLA', 'Planejada'), ('LIB', 'Liberada para Produção'), ('EXE', 'Em Execução'), ('CON', 'Concluída'), ('CAN', 'Cancelada')], default='PLA', max_length=3),
        ),
    ]
