# Generated by Django 5.2.4 on 2025-11-09 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0040_alter_projeto_options_alter_demanda_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInstalacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, help_text='Quantidade do acessório necessária por instalação.', max_digits=10)),
                ('item_acessorio', models.ForeignKey(help_text='O item necessário para a instalação (cabo, suporte, etc.)', on_delete=django.db.models.deletion.PROTECT, to='Atividades.item')),
                ('produto_pai', models.ForeignKey(help_text='O produto principal que será instalado.', on_delete=django.db.models.deletion.CASCADE, related_name='itens_instalacao', to='Atividades.produtofabricado')),
            ],
            options={
                'verbose_name': 'Item de Instalação',
                'verbose_name_plural': 'Itens de Instalação (Kit)',
                'unique_together': {('produto_pai', 'item_acessorio')},
            },
        ),
    ]
