# Generated by Django 5.2.4 on 2025-11-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0041_iteminstalacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanda',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='demanda',
            name='quantidade_reserva',
            field=models.IntegerField(blank=True, default=0, verbose_name='Qtd. Reserva'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='quantidade_total',
            field=models.IntegerField(default=0, verbose_name='Qtd. Total'),
            preserve_default=False,
        ),
    ]
