# Generated by Django 5.2.3 on 2025-11-10 15:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0043_alter_ordemproducao_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgrupamentoVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_por_volume', models.DecimalField(decimal_places=2, help_text='Ex: 16 (unidades por caixa)', max_digits=10, verbose_name='Qtd. por Volume')),
                ('numero_de_volumes', models.PositiveIntegerField(default=1, help_text='Ex: 9 (caixas neste lote)', verbose_name='Nº de Volumes')),
                ('data_embalado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('codigo_lote', models.CharField(blank=True, help_text='Código único de rastreio deste lote (ex: LOTE-0001)', max_length=20, unique=True)),
                ('produto', models.ForeignKey(help_text='O material que foi embalado.', on_delete=django.db.models.deletion.PROTECT, to='Atividades.item')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agrupamentos_volume', to='Atividades.projeto')),
            ],
            options={
                'verbose_name': 'Agrupamento de Volume',
                'verbose_name_plural': 'Agrupamentos de Volume',
                'ordering': ['projeto', '-data_embalado'],
            },
        ),
    ]
