# Generated by Django 5.2.4 on 2025-11-15 03:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0044_agrupamentovolume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_volume', models.CharField(blank=True, help_text='Código único de rastreio deste volume (ex: VOL-0001)', max_length=20, unique=True)),
                ('data_embalado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volumes', to='Atividades.projeto')),
            ],
            options={
                'verbose_name': 'Volume (Caixa/Pallet)',
                'verbose_name_plural': 'Volumes (Caixas/Pallets)',
                'ordering': ['-data_embalado'],
            },
        ),
        migrations.CreateModel(
            name='ItemVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='Quantidade deste produto neste volume.', max_digits=10, verbose_name='Quantidade')),
                ('produto', models.ForeignKey(help_text='O produto/material dentro da caixa.', on_delete=django.db.models.deletion.PROTECT, to='Atividades.item')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_dentro', to='Atividades.volume')),
            ],
            options={
                'verbose_name': 'Item no Volume',
                'verbose_name_plural': 'Itens no Volume',
                'unique_together': {('volume', 'produto')},
            },
        ),
        migrations.DeleteModel(
            name='AgrupamentoVolume',
        ),
    ]
