# Generated by Django 5.2.3 on 2025-11-23 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0045_volume_itemvolume_delete_agrupamentovolume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ['-data_embalado'], 'verbose_name': 'Volume', 'verbose_name_plural': 'Volumes'},
        ),
    ]
