# Generated by Django 5.2.3 on 2025-11-14 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividades', '0045_volume_itemvolume_delete_agrupamentovolume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemvolume',
            options={'verbose_name': 'Item no Volume', 'verbose_name_plural': 'Itens no Volume'},
        ),
        migrations.AlterUniqueTogether(
            name='itemvolume',
            unique_together={('volume', 'produto')},
        ),
        migrations.AlterField(
            model_name='itemvolume',
            name='produto',
            field=models.ForeignKey(help_text='O produto/material dentro da caixa.', on_delete=django.db.models.deletion.PROTECT, to='Atividades.item'),
        ),
        migrations.RemoveField(
            model_name='itemvolume',
            name='codigo_lote',
        ),
        migrations.RemoveField(
            model_name='itemvolume',
            name='data_embalado',
        ),
        migrations.RemoveField(
            model_name='itemvolume',
            name='numero_de_volumes',
        ),
        migrations.RemoveField(
            model_name='itemvolume',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='itemvolume',
            name='quantidade_por_volume',
        ),
    ]
